# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         OCR-Naive
version:      0.03
version_from: Naive.pm
installdirs:  site
requires:
    IPA:                           0
    Prima:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
