--- #YAML:1.0
name:                OCR-Naive
version:             0.07
abstract:            convert images into text in an extremely naive fashion
license:             ~
author:              
    - Dmitry Karasik <dmitry@karasik.eu.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IPA:                           0
    Prima:                         0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
